version: "3.5"
services:
    servicediscovery:
      container_name: SD
      build: ServiceDiscovery
      ports:
        - 9000:9000
      expose:
        - 9000
      networks:
        network:
          ipv4_address: 172.160.22.20
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.160.22.0/24
